### ISSUE TITLE
Tmux message-style

### ISSUE THREAD

**Issue by aharris88** [trevordmiller/nova-example-dotfiles#3]
You might want to add something like this:

    set -g message-style 'fg=yellow, bg=black'

Here is how it looks normally:

![screen shot 2016-09-21 at 1 50 39 pm](https://cloud.githubusercontent.com/assets/3266363/18726661/b9189d1c-8002-11e6-9c5b-acb996b14c1c.png)

And here is how it looks with this setting:

![screen shot 2016-09-21 at 1 51 18 pm](https://cloud.githubusercontent.com/assets/3266363/18726668/bdf54470-8002-11e6-88fa-f424abaccb1d.png)

**Comment by trevordmiller** [comment]
@aharris88 Good catch. I agree. However, I'd probably recommend using `set -g message-style 'fg=cyan, bg=black'` instead of `yellow`, to use the color meanings of current user state, since this only shows up while you are in that mode right? Would you like to submit a pull request? There are contributing instructions on http://trevordmiller.com/nova. I'm happy to do this as well if you aren't interested.

**Comment by trevordmiller** [comment]
@aharris88 Actually, this is the only repo that doesn't have a process or continuous integration of all the `nova-*` repos, so this one you could just submit a pull request directly from a fork. Let me know if you want to, if not I'll take care of it no problem :)
